'''
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first 10 terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
1: 1
3: 1, 3
6: 1, 2, 3, 6
10: 1, 2, 5, 10
15: 1, 3, 5, 15
21: 1, 3, 7, 21
28: 1, 2, 4, 7, 14, 28

We can see that 28 is the first triangle number to have over 5 divisors.
What is the value of the first triangle number to have over five hundred divisors?
'''

import math

N = 500

triangle_number = 0
for x in range(1, math.factorial(500)): # high upper bound, we know 500! has 500 divisors
  triangle_number += x

  factors = 2 # 1 and itself
  for y in range(2, math.floor(math.sqrt(triangle_number))+1):
    if triangle_number % y == 0: # if divisor
      factors += 2

  if factors > N:
    print(triangle_number)
    break