'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''
from collections import deque

ans = 2 # need to add the initial 2
last_2 = deque([1, 2])

x = sum(last_2)
while x <= 4_000_000:
  last_2.popleft()
  last_2.append(x)
  if x % 2 == 0:
    ans += x
  x = sum(last_2)

print(ans)